// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1eupky93YAncVSArlwt5sxlhFeRDgVLo',
    appId: '1:305921677530:web:c2e0b4584e91c23978ede3',
    messagingSenderId: '305921677530',
    projectId: 'todo-app-b4b40',
    authDomain: 'todo-app-b4b40.firebaseapp.com',
    storageBucket: 'todo-app-b4b40.firebasestorage.app',
    measurementId: 'G-194PFNKPTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArvf_xHkPjdBFBNxFy35Ak2mbX9XcX2uo',
    appId: '1:305921677530:android:06d1dceea6d215c978ede3',
    messagingSenderId: '305921677530',
    projectId: 'todo-app-b4b40',
    storageBucket: 'todo-app-b4b40.firebasestorage.app',
  );
}
